### ISSUE TITLE
constant polling of a http://file/socket.io results in ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by wortkrieg** [MarlBurroW/Streamdeck-Uptime-Kuma#2]
Just a minor issue but worth mentioning, I guess.

debugger logs me the following error every few seconds, on PI as well as on the app itself: 

<img width="652" alt="Bildschirm­foto 2023-01-06 um 09 49 36" src="https://user-images.githubusercontent.com/35509013/210965915-b68e7ed3-7e96-43cb-bce9-1bab316707ac.png">

It may happen because I haven't set a valid Kuma URL yet.

**Comment by MarlBurroW** [comment]
Thanks for the feedback.
Currently, the plugin start trying to connect to the Kuma socket as soon as it is instantiated (So as soon as you drag&drop at least one button on your deck), and before you start to fill the connection settings.
I'll fix this by start connection only once the user has filled the connection related settings (url, login, password).

**Comment by MarlBurroW** [comment]
This [commit](https://github.com/MarlBurroW/Streamdeck-Uptime-Kuma/commit/08b534efa91465743d8b03fcb423fa2e7ed18091) should resolve this issue.
Will be published in the next release.

**Comment by wortkrieg** [comment]
Thanks for the fix. Tested with 1.1.2 and the issue is gone :)
